#!/usr/bin/env python3
"""Exports the toolbar icons from art/icon.json: every coat and state at 16, 32, 48, 96 and 128 px, whole-pixel
nearest-neighbour scaling, transparent background. Standard library only (a tiny PNG writer), so the repo keeps no
dependencies.

    python3 art/export.py        # writes extension/icons/<coat>/<icon|rec>-<size>.png and extension/dog.js

The PNGs are the store/manifest icons; dog.js carries the same grids so the extension can draw the dog at runtime in
any colours the user picks.
"""
import json
import os
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = (16, 32, 48, 96, 128)
NAMES = {"icon": "icon", "recording": "rec"}


def png(rows, path):
    """rows: list of lists of (r, g, b, a) tuples."""
    raw = b"".join(b"\x00" + bytes(c for px in row for c in px) for row in rows)
    chunk = lambda t, d: struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xFFFFFFFF)
    head = struct.pack(">IIBBBBB", len(rows[0]), len(rows), 8, 6, 0, 0, 0)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", head) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def main():
    doc = json.load(open(os.path.join(HERE, "icon.json")))
    for coat, art in doc["coats"].items():
        colour = {ch: tuple(int(h[i:i + 2], 16) for i in (1, 3, 5)) + (255,) for ch, h in zip(art["letters"], art["palette"])}
        colour["."] = (0, 0, 0, 0)
        out = os.path.join(HERE, "..", "extension", "icons", coat)
        os.makedirs(out, exist_ok=True)
        for state, frames in art["states"].items():
            frame = frames[0]
            for size in SIZES:
                k = size // len(frame)
                rows = [[colour[ch] for ch in row for _ in range(k)] for row in frame for _ in range(k)]
                png(rows, os.path.join(out, f"{NAMES[state]}-{size}.png"))
        print(out)
    with open(os.path.join(HERE, "..", "extension", "dog.js"), "w") as f:
        f.write("/** Generated by art/export.py from art/icon.json: the dog's pixel grids and preset coats. Do not edit by hand. */\n")
        f.write("const DOG = " + json.dumps(doc["coats"], separators=(",", ":")) + ";\n")
        f.write(DOG_JS)


DOG_JS = r"""
/** Colour roles a user can change on the Custom coat; eyes, nose, outline and glint stay as drawn. */
const DOG_ROLES = { coat: 'd', muzzle: 'o', ears: 'b', bandana: 'r' };

/** The palette for a coat name, or the dapple grid recoloured with {coat, muzzle, ears, bandana} for 'custom'. */
function dogArt(coat, colors) {
  if (DOG[coat]) return DOG[coat];
  const base = DOG.dapple;
  const palette = base.palette.slice();
  for (const [role, letter] of Object.entries(DOG_ROLES)) {
    const i = base.letters.indexOf(letter);
    if (i >= 0 && colors && /^#[0-9a-f]{6}$/i.test(colors[role] || '')) palette[i] = colors[role];
  }
  return { letters: base.letters, palette, states: base.states };
}

/** Source index for each of `size` target pixels over `n` source pixels; the extra pixels go to the outermost first. */
function spread(n, size) {
  const widths = Array(n).fill(Math.floor(size / n));
  const order = [...Array(n).keys()].sort((a, b) => Math.abs(b - (n - 1) / 2) - Math.abs(a - (n - 1) / 2));
  const extra = size - widths[0] * n;
  for (let i = 0; i < extra; i++) widths[order[i % n]]++;
  return widths.flatMap((w, i) => Array(w).fill(i));
}

/**
 * The dog as ImageData at `size` px; state is 'icon' or 'recording'. Whole-pixel scaling by default. With `fill`
 * (the toolbar icon) the empty margin and the outline-only side columns are trimmed and the rest is stretched to fill
 * the square, the extra pixels going to the outer ears/head/chin so the eyes and snout stay even.
 */
function dogImage(coat, colors, state, size, fill) {
  const art = dogArt(coat, colors);
  let frame = art.states[state][0];
  if (fill) {
    const blank = (s) => /^[.]*$/.test(s);
    frame = frame.filter((r) => !blank(r));
    const cols = (x) => frame.map((r) => r[x]).join('');
    while (frame[0].length > 1 && /^[.k]*$/.test(cols(0))) frame = frame.map((r) => r.slice(1));
    while (frame[0].length > 1 && /^[.k]*$/.test(cols(frame[0].length - 1))) frame = frame.map((r) => r.slice(0, -1));
    const n = Math.max(frame.length, frame[0].length);
    const top = Math.floor((n - frame.length) / 2), left = Math.floor((n - frame[0].length) / 2);
    frame = [...Array(n)].map((_, y) => [...Array(n)].map((__, x) => (frame[y - top] || '')[x - left] || '.').join(''));
  }
  const n = frame.length;
  const map = fill ? spread(n, size) : [...Array(size).keys()].map((t) => (t < n * Math.max(1, Math.floor(size / n)) ? Math.floor(t / Math.max(1, Math.floor(size / n))) : -1));
  const rgb = art.palette.map((hex) => [1, 3, 5].map((o) => parseInt(hex.slice(o, o + 2), 16)));
  const px = new Uint8ClampedArray(size * size * 4);
  for (let ty = 0; ty < size; ty++) {
    const sy = map[ty];
    if (sy < 0) continue;
    for (let tx = 0; tx < size; tx++) {
      const sx = map[tx];
      const i = sx < 0 ? -1 : art.letters.indexOf(frame[sy][sx]);
      if (i >= 0) px.set([...rgb[i], 255], (ty * size + tx) * 4);
    }
  }
  return new ImageData(px, size, size);
}

if (typeof module !== 'undefined') module.exports = { DOG, dogArt, dogImage, spread };
"""


if __name__ == "__main__":
    main()
